import type {
  Patient,
  Address,
  FleetOption,
  TNCOption,
  MarketplaceOption,
  TripRequest,
  TripConstraints,
  Trip,
  TripStatus,
  StatusHistoryEntry,
  Companion,
  LevelOfService,
  FundingSource,
  SourceMetadata,
  Vehicle,
  Driver,
  MarketplaceTrip,
  MarketplaceOffer,
  MarketplaceTripStatus,
  MarketplaceOfferStatus,
  PricingResult,
  PricingFactor,
  ActiveTracking,
  HealthPlan,
  AuthorizationRule,
  BrokerTripImport,
  Claim,
  ClaimStatus,
  BrokerSystem,
  SyncStatus,
  ComplianceMetric,
} from "@/lib/types";

// ============================================================================
// Helper: dynamic timestamps relative to now
// ============================================================================

function timeFromNow(minutesFromNow: number): string {
  const d = new Date();
  d.setMinutes(d.getMinutes() + minutesFromNow);
  return d.toISOString();
}

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function todayAt(hours: number, minutes: number): string {
  const d = new Date();
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

// ============================================================================
// Patients (extended with eligibility, email, healthPlanId, etc.)
// ============================================================================

const mariaGonzalez: Patient = {
  id: "pat-001",
  firstName: "Maria",
  lastName: "Gonzalez",
  dateOfBirth: "1958-03-15",
  memberId: "MBR-44892",
  phone: "(602) 555-0134",
  email: "maria.gonzalez@email.com",
  healthPlanId: "hp-az-medicaid-001",
  eligibilityStatus: "eligible",
  authorizedTripsRemaining: 18,
  preferredLanguage: "Spanish",
  mobilityType: "wheelchair",
  needsEscort: true,
  specialNeeds: [],
};

const jamesWashington: Patient = {
  id: "pat-002",
  firstName: "James",
  lastName: "Washington",
  dateOfBirth: "1945-11-22",
  memberId: "MBR-33107",
  phone: "(602) 555-0278",
  email: "j.washington45@email.com",
  healthPlanId: "hp-az-medicare-002",
  eligibilityStatus: "eligible",
  authorizedTripsRemaining: 6,
  preferredLanguage: "English",
  mobilityType: "ambulatory",
  needsEscort: false,
  specialNeeds: ["oxygen"],
};

const dorothyChen: Patient = {
  id: "pat-003",
  firstName: "Dorothy",
  lastName: "Chen",
  dateOfBirth: "1940-07-09",
  memberId: "MBR-55201",
  phone: "(602) 555-0391",
  email: "dorothy.chen@email.com",
  healthPlanId: "hp-az-medicaid-001",
  eligibilityStatus: "pending_verification",
  authorizedTripsRemaining: 0,
  preferredLanguage: "Mandarin",
  mobilityType: "stretcher",
  needsEscort: true,
  specialNeeds: ["bariatric"],
};

const robertKim: Patient = {
  id: "pat-004",
  firstName: "Robert",
  lastName: "Kim",
  dateOfBirth: "1972-01-30",
  memberId: "MBR-21058",
  phone: "(602) 555-0445",
  email: "rkim72@email.com",
  healthPlanId: "hp-az-commercial-003",
  eligibilityStatus: "eligible",
  authorizedTripsRemaining: 42,
  preferredLanguage: "English",
  mobilityType: "ambulatory",
  needsEscort: false,
  specialNeeds: [],
};

// ============================================================================
// Phoenix AZ Addresses
// ============================================================================

const mariasHome: Address = {
  label: "Home",
  street: "1234 E Oak St",
  city: "Phoenix",
  state: "AZ",
  zip: "85006",
  lat: 33.4484,
  lng: -112.0548,
};

const jamesHome: Address = {
  label: "Home",
  street: "890 W Camelback Rd",
  city: "Phoenix",
  state: "AZ",
  zip: "85013",
  lat: 33.5093,
  lng: -112.0853,
};

const dorothyHome: Address = {
  label: "Home",
  street: "3400 N Central Ave",
  city: "Phoenix",
  state: "AZ",
  zip: "85012",
  lat: 33.4942,
  lng: -112.0739,
};

const robertsHome: Address = {
  label: "Home",
  street: "5678 E McDowell Rd",
  city: "Phoenix",
  state: "AZ",
  zip: "85008",
  lat: 33.4655,
  lng: -111.9988,
};

const kaiserCentral: Address = {
  label: "Kaiser Permanente Central",
  street: "2100 E Highland Ave",
  city: "Phoenix",
  state: "AZ",
  zip: "85016",
  lat: 33.5097,
  lng: -112.0344,
};

const bannerUniversity: Address = {
  label: "Banner University Medical Center",
  street: "1111 E McDowell Rd",
  city: "Phoenix",
  state: "AZ",
  zip: "85006",
  lat: 33.4562,
  lng: -112.0407,
};

const stJosephs: Address = {
  label: "St. Joseph's Hospital & Medical Center",
  street: "350 W Thomas Rd",
  city: "Phoenix",
  state: "AZ",
  zip: "85013",
  lat: 33.4813,
  lng: -112.0815,
};

const mayoClinicPhoenix: Address = {
  label: "Mayo Clinic - Phoenix",
  street: "5777 E Mayo Blvd",
  city: "Phoenix",
  state: "AZ",
  zip: "85054",
  lat: 33.6598,
  lng: -111.9578,
};

// ============================================================================
// Token map (simulates Salesforce deep-link resolution)
// ============================================================================

export interface TokenData {
  patient: Patient;
  pickup: Address;
  dropoff: Address;
  salesforceRecordId: string;
}

export const TOKEN_MAP: Record<string, TokenData> = {
  abc123: {
    patient: mariaGonzalez,
    pickup: mariasHome,
    dropoff: kaiserCentral,
    salesforceRecordId: "SF-CASE-2026-00891",
  },
  def456: {
    patient: jamesWashington,
    pickup: jamesHome,
    dropoff: bannerUniversity,
    salesforceRecordId: "SF-CASE-2026-00892",
  },
  ghi789: {
    patient: dorothyChen,
    pickup: dorothyHome,
    dropoff: stJosephs,
    salesforceRecordId: "SF-CASE-2026-00893",
  },
  jkl012: {
    patient: robertKim,
    pickup: robertsHome,
    dropoff: mayoClinicPhoenix,
    salesforceRecordId: "SF-CASE-2026-00894",
  },
};

// ============================================================================
// Fleet options (1 feasible, 1 infeasible)
// ============================================================================

export function getMockFleetOptions(constraints: TripConstraints): FleetOption[] {
  const feasible: FleetOption = {
    type: "fleet",
    id: "fleet-001",
    feasible: true,
    vehicleId: "V-102",
    driverName: "Carlos Mendez",
    vehicleType: "WAV Van",
    estimatedPickupTime: timeFromNow(25),
    additionalMiles: 8.3,
    additionalMinutes: 22,
    internalCost: 18.5,
    tripsImpacted: [
      {
        tripId: "T-4401",
        patientName: "Helen Park",
        delayMinutes: 12,
        description: "Pickup delayed from 2:15 PM to 2:27 PM",
      },
    ],
    scheduleChanges: [
      "Reorder stops on Route 7: move T-4401 after new trip",
      "Driver shift extended by ~15 min",
    ],
    confidence: 0.85,
  };

  const infeasible: FleetOption = {
    type: "fleet",
    id: "fleet-002",
    feasible: false,
    estimatedPickupTime: "",
    additionalMiles: 0,
    additionalMinutes: 0,
    internalCost: 0,
    tripsImpacted: [],
    scheduleChanges: [],
    confidence: 0,
    reasons: [
      constraints.mobilityType === "wheelchair"
        ? "No WAV vehicles available in requested window"
        : constraints.mobilityType === "stretcher"
          ? "No stretcher-capable vehicles available"
          : "No vehicles available in requested window",
      "Nearest available vehicle is 45+ min away",
      "Would exceed driver hours-of-service limit",
    ],
  };

  return [feasible, infeasible];
}

// ============================================================================
// TNC options (3 options)
// ============================================================================

export function getMockTNCOptions(): TNCOption[] {
  return [
    {
      type: "tnc",
      id: "tnc-001",
      provider: "uber",
      providerDisplayName: "Uber",
      serviceLevel: "Uber WAV",
      etaMinutes: 14,
      cost: 32.5,
      surgeMultiplier: 1.0,
      capabilities: ["wheelchair_accessible"],
      estimatedPickupTime: timeFromNow(14),
    },
    {
      type: "tnc",
      id: "tnc-002",
      provider: "uber",
      providerDisplayName: "Uber",
      serviceLevel: "UberXL",
      etaMinutes: 8,
      cost: 28.0,
      surgeMultiplier: 1.2,
      capabilities: [],
      estimatedPickupTime: timeFromNow(8),
    },
    {
      type: "tnc",
      id: "tnc-003",
      provider: "lyft",
      providerDisplayName: "Lyft",
      serviceLevel: "Lyft XL",
      etaMinutes: 11,
      cost: 30.0,
      surgeMultiplier: 1.0,
      capabilities: [],
      estimatedPickupTime: timeFromNow(11),
    },
  ];
}

// ============================================================================
// Marketplace options (3 providers)
// ============================================================================

export function getMockMarketplaceOptions(): MarketplaceOption[] {
  return [
    {
      type: "marketplace",
      id: "mp-001",
      providerName: "Valley Medical Transport",
      providerRating: 4.8,
      reliabilityScore: 94,
      etaMinutes: 20,
      cost: 26.0,
      capabilities: ["wheelchair_accessible", "stretcher", "oxygen"],
      estimatedPickupTime: timeFromNow(20),
      completedTrips: 1247,
    },
    {
      type: "marketplace",
      id: "mp-002",
      providerName: "Desert Care Rides",
      providerRating: 4.2,
      reliabilityScore: 87,
      etaMinutes: 15,
      cost: 29.5,
      capabilities: ["wheelchair_accessible", "oxygen"],
      estimatedPickupTime: timeFromNow(15),
      completedTrips: 523,
    },
    {
      type: "marketplace",
      id: "mp-003",
      providerName: "Southwest NEMT Services",
      providerRating: 4.6,
      reliabilityScore: 91,
      etaMinutes: 30,
      cost: 22.0,
      capabilities: ["wheelchair_accessible", "stretcher", "oxygen", "bariatric"],
      estimatedPickupTime: timeFromNow(30),
      completedTrips: 892,
    },
  ];
}

// ============================================================================
// Build full TripRequest from token data (extended fields)
// ============================================================================

export function buildTripRequestFromToken(
  token: string,
  data: TokenData
): TripRequest {
  const now = new Date();
  const timeStr = `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;
  const dateStr = now.toISOString().split("T")[0];

  return {
    id: "",
    patient: data.patient,
    pickup: data.pickup,
    dropoff: data.dropoff,
    requestedDate: dateStr,
    requestedTime: timeStr,
    tripType: "one_way",
    constraints: {
      mobilityType: data.patient.mobilityType,
      needsEscort: data.patient.needsEscort,
      escortCount: data.patient.needsEscort ? 1 : 0,
      specialNeeds: [...data.patient.specialNeeds],
      companions: [],
    },
    notes: "",
    source: {
      system: "salesforce",
      recordId: data.salesforceRecordId,
      token,
      prefilled: true,
      timestamp: now.toISOString(),
    },
    willCall: false,
    companions: [],
    levelOfService: data.patient.mobilityType as LevelOfService,
    fundingSource: "medicaid",
  };
}

// ============================================================================
// Mock facility trips (8 trips in various statuses for dashboard)
// ============================================================================

function buildStatusHistory(
  statuses: { status: TripStatus; minutesAgo: number; note?: string }[]
): StatusHistoryEntry[] {
  return statuses.map((s) => ({
    status: s.status,
    timestamp: timeFromNow(-s.minutesAgo),
    note: s.note,
  }));
}

function buildDashboardRequest(
  patient: Patient,
  pickup: Address,
  dropoff: Address,
  overrides: Partial<TripRequest> = {}
): TripRequest {
  const now = new Date();
  const dateStr = now.toISOString().split("T")[0];

  return {
    id: overrides.id ?? "",
    patient,
    pickup,
    dropoff,
    requestedDate: dateStr,
    requestedTime: overrides.requestedTime ?? "09:00",
    appointmentTime: overrides.appointmentTime,
    tripType: overrides.tripType ?? "one_way",
    constraints: overrides.constraints ?? {
      mobilityType: patient.mobilityType,
      needsEscort: patient.needsEscort,
      escortCount: patient.needsEscort ? 1 : 0,
      specialNeeds: [...patient.specialNeeds],
      companions: [],
    },
    notes: overrides.notes ?? "",
    source: overrides.source ?? {
      system: "salesforce",
      recordId: "SF-CASE-2026-00900",
      prefilled: true,
      timestamp: daysAgo(1),
    },
    willCall: overrides.willCall ?? false,
    companions: overrides.companions ?? [],
    levelOfService: overrides.levelOfService ?? (patient.mobilityType as LevelOfService),
    fundingSource: overrides.fundingSource ?? "medicaid",
    scheduledReturn: overrides.scheduledReturn,
    authorizationNumber: overrides.authorizationNumber,
  };
}

export const MOCK_FACILITY_TRIPS: Trip[] = [
  // 1. Completed trip
  {
    id: "trip-2001",
    request: buildDashboardRequest(mariaGonzalez, mariasHome, kaiserCentral, {
      requestedTime: "08:00",
      appointmentTime: "09:00",
      levelOfService: "wheelchair",
      fundingSource: "medicaid",
      authorizationNumber: "AUTH-90001",
    }),
    status: "completed",
    fulfillment: {
      type: "fleet",
      id: "fleet-done-001",
      feasible: true,
      vehicleId: "V-102",
      driverName: "Carlos Mendez",
      vehicleType: "WAV Van",
      estimatedPickupTime: daysAgo(2),
      additionalMiles: 6.1,
      additionalMinutes: 18,
      internalCost: 16.0,
      tripsImpacted: [],
      scheduleChanges: [],
      confidence: 1.0,
    },
    assignedVehicleId: "V-102",
    assignedDriverId: "drv-010",
    authorization: {
      id: "auth-2001",
      status: "approved",
      authorizedAt: daysAgo(3),
      expiresAt: timeFromNow(60 * 24 * 27),
    },
    statusHistory: buildStatusHistory([
      { status: "requested", minutesAgo: 2880, note: "Trip requested via Salesforce" },
      { status: "authorized", minutesAgo: 2850 },
      { status: "assigned", minutesAgo: 2820 },
      { status: "dispatched", minutesAgo: 2810 },
      { status: "en_route_pickup", minutesAgo: 2795 },
      { status: "arrived_pickup", minutesAgo: 2780 },
      { status: "picked_up", minutesAgo: 2775 },
      { status: "in_transit", minutesAgo: 2770 },
      { status: "arrived_dropoff", minutesAgo: 2745 },
      { status: "completed", minutesAgo: 2740, note: "Trip completed on time" },
    ]),
    willCall: false,
    completionData: {
      actualPickupTime: daysAgo(2),
      actualDropoffTime: daysAgo(2),
      actualMiles: 7.2,
      waitTime: 3,
      signatures: [{ signedBy: "Maria Gonzalez", signedAt: daysAgo(2) }],
      odometer: { start: 54210, end: 54217 },
    },
  },

  // 2. In transit
  {
    id: "trip-2002",
    request: buildDashboardRequest(jamesWashington, jamesHome, bannerUniversity, {
      requestedTime: "10:30",
      appointmentTime: "11:15",
      levelOfService: "ambulatory",
      fundingSource: "medicare",
      authorizationNumber: "AUTH-90002",
    }),
    status: "in_transit",
    fulfillment: {
      type: "marketplace",
      id: "mp-active-001",
      providerName: "Valley Medical Transport",
      providerRating: 4.8,
      reliabilityScore: 94,
      etaMinutes: 12,
      cost: 26.0,
      capabilities: ["oxygen"],
      estimatedPickupTime: timeFromNow(-15),
      completedTrips: 1247,
    },
    assignedVehicleId: "V-MP-088",
    assignedDriverId: "drv-mp-022",
    authorization: {
      id: "auth-2002",
      status: "approved",
      authorizedAt: daysAgo(1),
      expiresAt: timeFromNow(60 * 24 * 29),
    },
    statusHistory: buildStatusHistory([
      { status: "requested", minutesAgo: 120 },
      { status: "authorized", minutesAgo: 115 },
      { status: "assigned", minutesAgo: 60 },
      { status: "dispatched", minutesAgo: 30 },
      { status: "en_route_pickup", minutesAgo: 25 },
      { status: "arrived_pickup", minutesAgo: 18 },
      { status: "picked_up", minutesAgo: 15, note: "Patient boarded with O2" },
      { status: "in_transit", minutesAgo: 14 },
    ]),
    trackingUrl: "https://track.mediroutes.com/trip-2002",
    willCall: false,
  },

  // 3. Dispatched (en route to pickup)
  {
    id: "trip-2003",
    request: buildDashboardRequest(robertKim, robertsHome, mayoClinicPhoenix, {
      requestedTime: "13:00",
      appointmentTime: "14:00",
      levelOfService: "ambulatory",
      fundingSource: "commercial",
    }),
    status: "en_route_pickup",
    fulfillment: {
      type: "tnc",
      id: "tnc-active-001",
      provider: "uber",
      providerDisplayName: "Uber",
      serviceLevel: "UberXL",
      etaMinutes: 6,
      cost: 34.0,
      surgeMultiplier: 1.0,
      capabilities: [],
      estimatedPickupTime: timeFromNow(6),
    },
    authorization: {
      id: "auth-2003",
      status: "approved",
      authorizedAt: daysAgo(0),
      expiresAt: timeFromNow(60 * 24 * 30),
    },
    statusHistory: buildStatusHistory([
      { status: "requested", minutesAgo: 90 },
      { status: "authorized", minutesAgo: 88 },
      { status: "assigned", minutesAgo: 20 },
      { status: "dispatched", minutesAgo: 15 },
      { status: "en_route_pickup", minutesAgo: 10 },
    ]),
    trackingUrl: "https://track.mediroutes.com/trip-2003",
    willCall: false,
  },

  // 4. Assigned (waiting for dispatch)
  {
    id: "trip-2004",
    request: buildDashboardRequest(dorothyChen, dorothyHome, stJosephs, {
      requestedTime: "14:30",
      appointmentTime: "15:30",
      levelOfService: "stretcher",
      fundingSource: "medicaid",
      willCall: true,
      authorizationNumber: "AUTH-90004",
    }),
    status: "assigned",
    fulfillment: {
      type: "fleet",
      id: "fleet-assigned-001",
      feasible: true,
      vehicleId: "V-108",
      driverName: "Angela Torres",
      vehicleType: "Stretcher Van",
      estimatedPickupTime: timeFromNow(45),
      additionalMiles: 4.2,
      additionalMinutes: 14,
      internalCost: 42.0,
      tripsImpacted: [],
      scheduleChanges: [],
      confidence: 0.92,
    },
    assignedVehicleId: "V-108",
    assignedDriverId: "drv-015",
    authorization: {
      id: "auth-2004",
      status: "approved",
      authorizedAt: daysAgo(1),
      expiresAt: timeFromNow(60 * 24 * 29),
    },
    statusHistory: buildStatusHistory([
      { status: "requested", minutesAgo: 180 },
      { status: "authorized", minutesAgo: 170 },
      { status: "assigned", minutesAgo: 60, note: "Stretcher van V-108 assigned" },
    ]),
    willCall: true,
  },

  // 5. Requested (awaiting authorization)
  {
    id: "trip-2005",
    request: buildDashboardRequest(mariaGonzalez, kaiserCentral, mariasHome, {
      requestedTime: "16:00",
      levelOfService: "wheelchair",
      fundingSource: "medicaid",
      tripType: "one_way",
      notes: "Return trip from Kaiser appointment",
    }),
    status: "requested",
    authorization: {
      id: "auth-2005",
      status: "pending",
    },
    statusHistory: buildStatusHistory([
      { status: "requested", minutesAgo: 30, note: "Return trip created" },
    ]),
    willCall: false,
  },

  // 6. Cancelled
  {
    id: "trip-2006",
    request: buildDashboardRequest(robertKim, robertsHome, bannerUniversity, {
      requestedTime: "09:00",
      appointmentTime: "10:00",
      levelOfService: "ambulatory",
      fundingSource: "commercial",
      notes: "Cancelled by patient - rescheduling",
    }),
    status: "cancelled",
    authorization: {
      id: "auth-2006",
      status: "approved",
      authorizedAt: daysAgo(3),
      expiresAt: timeFromNow(60 * 24 * 27),
    },
    statusHistory: buildStatusHistory([
      { status: "requested", minutesAgo: 4320 },
      { status: "authorized", minutesAgo: 4300 },
      { status: "assigned", minutesAgo: 4200 },
      { status: "cancelled", minutesAgo: 2880, note: "Patient cancelled - appointment rescheduled" },
    ]),
    willCall: false,
  },

  // 7. No show
  {
    id: "trip-2007",
    request: buildDashboardRequest(jamesWashington, jamesHome, mayoClinicPhoenix, {
      requestedTime: "07:30",
      appointmentTime: "09:00",
      levelOfService: "ambulatory",
      fundingSource: "medicare",
    }),
    status: "no_show",
    fulfillment: {
      type: "marketplace",
      id: "mp-ns-001",
      providerName: "Desert Care Rides",
      providerRating: 4.2,
      reliabilityScore: 87,
      etaMinutes: 15,
      cost: 35.0,
      capabilities: ["oxygen"],
      estimatedPickupTime: daysAgo(1),
      completedTrips: 523,
    },
    assignedVehicleId: "V-MP-045",
    assignedDriverId: "drv-mp-011",
    authorization: {
      id: "auth-2007",
      status: "approved",
      authorizedAt: daysAgo(2),
      expiresAt: timeFromNow(60 * 24 * 28),
    },
    statusHistory: buildStatusHistory([
      { status: "requested", minutesAgo: 1800 },
      { status: "authorized", minutesAgo: 1790 },
      { status: "assigned", minutesAgo: 1500 },
      { status: "dispatched", minutesAgo: 1470 },
      { status: "en_route_pickup", minutesAgo: 1455 },
      { status: "arrived_pickup", minutesAgo: 1440 },
      { status: "no_show", minutesAgo: 1425, note: "Patient not present after 15 min wait" },
    ]),
    willCall: false,
  },

  // 8. Authorized (ready to be matched)
  {
    id: "trip-2008",
    request: buildDashboardRequest(dorothyChen, stJosephs, dorothyHome, {
      requestedTime: "17:00",
      levelOfService: "stretcher",
      fundingSource: "medicaid",
      tripType: "one_way",
      notes: "Discharge transport - bariatric stretcher required",
      companions: [{ name: "Linda Chen", relationship: "Daughter", phone: "(602) 555-0412" }],
      authorizationNumber: "AUTH-90008",
    }),
    status: "authorized",
    authorization: {
      id: "auth-2008",
      status: "approved",
      authorizedAt: timeFromNow(-45),
      expiresAt: timeFromNow(60 * 24 * 30),
    },
    statusHistory: buildStatusHistory([
      { status: "requested", minutesAgo: 60, note: "Discharge trip via EHR event" },
      { status: "authorized", minutesAgo: 45, note: "Auto-approved per health plan rules" },
    ]),
    willCall: false,
  },
];

// ============================================================================
// Helper: future date relative to today
// ============================================================================

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

// ============================================================================
// Provider Vehicles — SafeRide Medical Transport
// ============================================================================

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "V-101",
    providerId: "provider-001",
    type: "wav_van",
    make: "Ford",
    model: "Transit",
    year: 2022,
    licensePlate: "AZ-7291",
    vin: "1FTBW2CM3NKA34201",
    capacity: { ambulatory: 3, wheelchair: 2, stretcher: 0 },
    equipment: ["wheelchair_ramp", "oxygen_hookup", "securement_system"],
    status: "available",
    currentLocation: { lat: 33.4489, lng: -112.0751 },
    fuelLevel: 0.75,
    mileage: 34200,
    lastInspection: daysAgo(18),
    credentials: [
      { type: "insurance", status: "current", expiryDate: daysFromNow(285) },
      { type: "registration", status: "current", expiryDate: daysFromNow(195) },
      { type: "inspection", status: "current", expiryDate: daysFromNow(160) },
    ],
  },
  {
    id: "V-102",
    providerId: "provider-001",
    type: "wav_van",
    make: "Mercedes-Benz",
    model: "Sprinter",
    year: 2023,
    licensePlate: "AZ-8354",
    vin: "W1Y4ECHY0NP123456",
    capacity: { ambulatory: 4, wheelchair: 2, stretcher: 0 },
    equipment: ["wheelchair_ramp", "wheelchair_lift", "oxygen_hookup", "securement_system"],
    status: "on_trip",
    currentLocation: { lat: 33.5102, lng: -112.0345 },
    fuelLevel: 0.6,
    mileage: 22100,
    lastInspection: daysAgo(12),
    credentials: [
      { type: "insurance", status: "current", expiryDate: daysFromNow(340) },
      { type: "registration", status: "current", expiryDate: daysFromNow(260) },
      { type: "inspection", status: "current", expiryDate: daysFromNow(175) },
    ],
  },
  {
    id: "V-103",
    providerId: "provider-001",
    type: "minivan",
    make: "Dodge",
    model: "Grand Caravan",
    year: 2021,
    licensePlate: "AZ-5127",
    vin: "2C4RDGCG8LR212345",
    capacity: { ambulatory: 4, wheelchair: 0, stretcher: 0 },
    equipment: ["first_aid_kit", "booster_seat"],
    status: "available",
    currentLocation: { lat: 33.4621, lng: -112.0983 },
    fuelLevel: 0.9,
    mileage: 45800,
    lastInspection: daysAgo(25),
    credentials: [
      { type: "insurance", status: "current", expiryDate: daysFromNow(210) },
      { type: "registration", status: "current", expiryDate: daysFromNow(305) },
      { type: "inspection", status: "current", expiryDate: daysFromNow(150) },
    ],
  },
  {
    id: "V-104",
    providerId: "provider-001",
    type: "minivan",
    make: "Toyota",
    model: "Sienna",
    year: 2023,
    licensePlate: "AZ-9408",
    vin: "5TDKRKEC2PS012345",
    capacity: { ambulatory: 4, wheelchair: 0, stretcher: 0 },
    equipment: ["first_aid_kit"],
    status: "on_trip",
    currentLocation: { lat: 33.4772, lng: -112.0612 },
    fuelLevel: 0.45,
    mileage: 18300,
    lastInspection: daysAgo(8),
    credentials: [
      { type: "insurance", status: "current", expiryDate: daysFromNow(350) },
      { type: "registration", status: "current", expiryDate: daysFromNow(280) },
      { type: "inspection", status: "current", expiryDate: daysFromNow(200) },
    ],
  },
  {
    id: "V-105",
    providerId: "provider-001",
    type: "stretcher_van",
    make: "Chevrolet",
    model: "Express",
    year: 2022,
    licensePlate: "AZ-6233",
    vin: "1GCWGAFG4N1234567",
    capacity: { ambulatory: 1, wheelchair: 0, stretcher: 1 },
    equipment: ["stretcher_mount", "oxygen_hookup", "suction_unit", "first_aid_kit"],
    status: "available",
    currentLocation: { lat: 33.4395, lng: -112.0482 },
    fuelLevel: 0.8,
    mileage: 28500,
    lastInspection: daysAgo(14),
    credentials: [
      { type: "insurance", status: "current", expiryDate: daysFromNow(270) },
      { type: "registration", status: "current", expiryDate: daysFromNow(230) },
      { type: "inspection", status: "current", expiryDate: daysFromNow(165) },
    ],
  },
  {
    id: "V-106",
    providerId: "provider-001",
    type: "bariatric_van",
    make: "Ford",
    model: "E-350",
    year: 2024,
    licensePlate: "AZ-1087",
    vin: "1FTSE3EL8RDA56789",
    capacity: { ambulatory: 2, wheelchair: 1, stretcher: 1 },
    equipment: ["bariatric_lift", "wheelchair_ramp", "reinforced_stretcher", "oxygen_hookup"],
    status: "off_duty",
    fuelLevel: 0.55,
    mileage: 8200,
    lastInspection: daysAgo(5),
    credentials: [
      { type: "insurance", status: "current", expiryDate: daysFromNow(365) },
      { type: "registration", status: "current", expiryDate: daysFromNow(340) },
      { type: "ada_compliance", status: "current", expiryDate: daysFromNow(290) },
    ],
  },
  {
    id: "V-107",
    providerId: "provider-001",
    type: "sedan",
    make: "Toyota",
    model: "Camry",
    year: 2022,
    licensePlate: "AZ-3745",
    vin: "4T1G11AK2NU789012",
    capacity: { ambulatory: 3, wheelchair: 0, stretcher: 0 },
    equipment: ["first_aid_kit"],
    status: "on_trip",
    currentLocation: { lat: 33.4558, lng: -112.0133 },
    fuelLevel: 0.35,
    mileage: 52100,
    lastInspection: daysAgo(30),
    credentials: [
      { type: "insurance", status: "current", expiryDate: daysFromNow(180) },
      { type: "registration", status: "current", expiryDate: daysFromNow(145) },
      { type: "inspection", status: "current", expiryDate: daysFromNow(120) },
    ],
  },
  {
    id: "V-108",
    providerId: "provider-001",
    type: "minivan",
    make: "Honda",
    model: "Odyssey",
    year: 2023,
    licensePlate: "AZ-4562",
    vin: "5FNRL6H70PB012345",
    capacity: { ambulatory: 4, wheelchair: 0, stretcher: 0 },
    equipment: ["first_aid_kit", "booster_seat"],
    status: "maintenance",
    fuelLevel: 0.7,
    mileage: 31400,
    lastInspection: daysAgo(3),
    credentials: [
      { type: "insurance", status: "current", expiryDate: daysFromNow(320) },
      { type: "registration", status: "current", expiryDate: daysFromNow(250) },
      { type: "inspection", status: "current", expiryDate: daysFromNow(185) },
    ],
  },
];

// ============================================================================
// Provider Drivers — SafeRide Medical Transport
// ============================================================================

export const MOCK_DRIVERS: Driver[] = [
  {
    id: "drv-010",
    providerId: "provider-001",
    firstName: "Carlos",
    lastName: "Mendez",
    phone: "(602) 555-0171",
    licenseNumber: "D1294837",
    licenseExpiry: daysFromNow(540),
    status: "available",
    rating: 4.9,
    completedTrips: 342,
    currentVehicleId: "V-101",
    credentials: [
      { type: "cpr", status: "current", expiryDate: daysFromNow(280), verifiedDate: daysAgo(85) },
      { type: "first_aid", status: "current", expiryDate: daysFromNow(280), verifiedDate: daysAgo(85) },
      { type: "defensive_driving", status: "current", expiryDate: daysFromNow(420), verifiedDate: daysAgo(145) },
      { type: "background_check", status: "current", expiryDate: daysFromNow(310), verifiedDate: daysAgo(55) },
      { type: "drug_test", status: "current", expiryDate: daysFromNow(150), verifiedDate: daysAgo(30) },
      { type: "hipaa", status: "current", expiryDate: daysFromNow(350), verifiedDate: daysAgo(15) },
    ],
  },
  {
    id: "drv-011",
    providerId: "provider-001",
    firstName: "Sarah",
    lastName: "Johnson",
    phone: "(602) 555-0238",
    licenseNumber: "D5738291",
    licenseExpiry: daysFromNow(480),
    status: "on_trip",
    rating: 4.7,
    completedTrips: 287,
    currentVehicleId: "V-102",
    credentials: [
      { type: "cpr", status: "current", expiryDate: daysFromNow(190), verifiedDate: daysAgo(175) },
      { type: "first_aid", status: "current", expiryDate: daysFromNow(190), verifiedDate: daysAgo(175) },
      { type: "defensive_driving", status: "expiring_soon", expiryDate: daysFromNow(28), verifiedDate: daysAgo(337) },
      { type: "background_check", status: "current", expiryDate: daysFromNow(265), verifiedDate: daysAgo(100) },
      { type: "drug_test", status: "current", expiryDate: daysFromNow(120), verifiedDate: daysAgo(60) },
    ],
  },
  {
    id: "drv-012",
    providerId: "provider-001",
    firstName: "Michael",
    lastName: "Okafor",
    phone: "(602) 555-0305",
    licenseNumber: "D8412056",
    licenseExpiry: daysFromNow(620),
    status: "available",
    rating: 4.8,
    completedTrips: 198,
    currentVehicleId: "V-103",
    credentials: [
      { type: "cpr", status: "current", expiryDate: daysFromNow(310), verifiedDate: daysAgo(55) },
      { type: "first_aid", status: "current", expiryDate: daysFromNow(310), verifiedDate: daysAgo(55) },
      { type: "defensive_driving", status: "current", expiryDate: daysFromNow(380), verifiedDate: daysAgo(75) },
      { type: "background_check", status: "current", expiryDate: daysFromNow(290), verifiedDate: daysAgo(75) },
      { type: "hipaa", status: "current", expiryDate: daysFromNow(345), verifiedDate: daysAgo(20) },
    ],
  },
  {
    id: "drv-013",
    providerId: "provider-001",
    firstName: "Lisa",
    lastName: "Park",
    phone: "(602) 555-0419",
    licenseNumber: "D3291748",
    licenseExpiry: daysFromNow(390),
    status: "on_trip",
    rating: 4.6,
    completedTrips: 156,
    currentVehicleId: "V-104",
    credentials: [
      { type: "cpr", status: "current", expiryDate: daysFromNow(220), verifiedDate: daysAgo(145) },
      { type: "first_aid", status: "expiring_soon", expiryDate: daysFromNow(18), verifiedDate: daysAgo(347) },
      { type: "defensive_driving", status: "current", expiryDate: daysFromNow(260), verifiedDate: daysAgo(105) },
      { type: "background_check", status: "current", expiryDate: daysFromNow(330), verifiedDate: daysAgo(35) },
      { type: "drug_test", status: "current", expiryDate: daysFromNow(140), verifiedDate: daysAgo(40) },
      { type: "hipaa", status: "current", expiryDate: daysFromNow(300), verifiedDate: daysAgo(65) },
    ],
  },
  {
    id: "drv-014",
    providerId: "provider-001",
    firstName: "James",
    lastName: "Robinson",
    phone: "(602) 555-0527",
    licenseNumber: "D6503891",
    licenseExpiry: daysFromNow(710),
    status: "available",
    rating: 4.9,
    completedTrips: 421,
    credentials: [
      { type: "cpr", status: "current", expiryDate: daysFromNow(340), verifiedDate: daysAgo(25) },
      { type: "first_aid", status: "current", expiryDate: daysFromNow(340), verifiedDate: daysAgo(25) },
      { type: "defensive_driving", status: "current", expiryDate: daysFromNow(400), verifiedDate: daysAgo(50) },
      { type: "background_check", status: "current", expiryDate: daysFromNow(350), verifiedDate: daysAgo(15) },
      { type: "drug_test", status: "current", expiryDate: daysFromNow(160), verifiedDate: daysAgo(20) },
      { type: "hipaa", status: "current", expiryDate: daysFromNow(365), verifiedDate: daysAgo(10) },
    ],
  },
  {
    id: "drv-015",
    providerId: "provider-001",
    firstName: "Angela",
    lastName: "Torres",
    phone: "(602) 555-0634",
    licenseNumber: "D9187254",
    licenseExpiry: daysFromNow(450),
    status: "on_trip",
    rating: 4.5,
    completedTrips: 89,
    currentVehicleId: "V-107",
    credentials: [
      { type: "cpr", status: "current", expiryDate: daysFromNow(200), verifiedDate: daysAgo(165) },
      { type: "first_aid", status: "current", expiryDate: daysFromNow(200), verifiedDate: daysAgo(165) },
      { type: "background_check", status: "current", expiryDate: daysFromNow(280), verifiedDate: daysAgo(85) },
      { type: "drug_test", status: "expiring_soon", expiryDate: daysFromNow(12), verifiedDate: daysAgo(168) },
    ],
  },
  {
    id: "drv-016",
    providerId: "provider-001",
    firstName: "David",
    lastName: "Nguyen",
    phone: "(602) 555-0742",
    licenseNumber: "D2746183",
    licenseExpiry: daysFromNow(580),
    status: "on_break",
    rating: 4.8,
    completedTrips: 267,
    credentials: [
      { type: "cpr", status: "current", expiryDate: daysFromNow(260), verifiedDate: daysAgo(105) },
      { type: "first_aid", status: "current", expiryDate: daysFromNow(260), verifiedDate: daysAgo(105) },
      { type: "defensive_driving", status: "current", expiryDate: daysFromNow(370), verifiedDate: daysAgo(90) },
      { type: "background_check", status: "current", expiryDate: daysFromNow(300), verifiedDate: daysAgo(65) },
      { type: "drug_test", status: "current", expiryDate: daysFromNow(155), verifiedDate: daysAgo(25) },
    ],
  },
  {
    id: "drv-017",
    providerId: "provider-001",
    firstName: "Maria",
    lastName: "Santos",
    phone: "(602) 555-0856",
    licenseNumber: "D4058396",
    licenseExpiry: daysFromNow(500),
    status: "off_duty",
    rating: 4.7,
    completedTrips: 312,
    credentials: [
      { type: "cpr", status: "current", expiryDate: daysFromNow(230), verifiedDate: daysAgo(135) },
      { type: "first_aid", status: "current", expiryDate: daysFromNow(230), verifiedDate: daysAgo(135) },
      { type: "defensive_driving", status: "current", expiryDate: daysFromNow(350), verifiedDate: daysAgo(110) },
      { type: "background_check", status: "current", expiryDate: daysFromNow(275), verifiedDate: daysAgo(90) },
      { type: "hipaa", status: "expiring_soon", expiryDate: daysFromNow(22), verifiedDate: daysAgo(343) },
      { type: "drug_test", status: "current", expiryDate: daysFromNow(130), verifiedDate: daysAgo(50) },
    ],
  },
];

// ============================================================================
// MARKETPLACE MOCK DATA
// ============================================================================

export interface MarketplaceProvider {
  id: string;
  name: string;
  rating: number;
  completedTrips: number;
  onTimePercent: number;
  coverageArea: string;
  capabilities: string[];
  activeVehicles: number;
  memberSince: string;
  verified: boolean;
}

export const MOCK_MARKETPLACE_PROVIDERS: MarketplaceProvider[] = [
  {
    id: "provider-001",
    name: "SafeRide Medical Transport",
    rating: 4.8,
    completedTrips: 2847,
    onTimePercent: 96,
    coverageArea: "Phoenix Metro, Scottsdale, Tempe, Mesa",
    capabilities: ["ambulatory", "wheelchair", "stretcher", "bariatric"],
    activeVehicles: 8,
    memberSince: "2021-03-15",
    verified: true,
  },
  {
    id: "provider-002",
    name: "Valley Medical Transport",
    rating: 4.6,
    completedTrips: 1523,
    onTimePercent: 93,
    coverageArea: "Phoenix, Glendale, Peoria, Surprise",
    capabilities: ["ambulatory", "wheelchair", "stretcher"],
    activeVehicles: 5,
    memberSince: "2022-01-10",
    verified: true,
  },
  {
    id: "provider-003",
    name: "Desert Care Rides",
    rating: 4.2,
    completedTrips: 876,
    onTimePercent: 89,
    coverageArea: "Chandler, Gilbert, Mesa, Tempe",
    capabilities: ["ambulatory", "wheelchair"],
    activeVehicles: 3,
    memberSince: "2023-06-20",
    verified: true,
  },
  {
    id: "provider-004",
    name: "Southwest NEMT Services",
    rating: 4.5,
    completedTrips: 1102,
    onTimePercent: 91,
    coverageArea: "Scottsdale, Fountain Hills, Cave Creek",
    capabilities: ["ambulatory", "wheelchair", "stretcher", "bariatric"],
    activeVehicles: 6,
    memberSince: "2022-08-05",
    verified: true,
  },
  {
    id: "provider-005",
    name: "Copper State Medical Transport",
    rating: 3.9,
    completedTrips: 412,
    onTimePercent: 85,
    coverageArea: "West Phoenix, Avondale, Goodyear",
    capabilities: ["ambulatory", "wheelchair"],
    activeVehicles: 2,
    memberSince: "2024-02-14",
    verified: false,
  },
  {
    id: "provider-006",
    name: "Sonoran Express NEMT",
    rating: 4.7,
    completedTrips: 1834,
    onTimePercent: 95,
    coverageArea: "Full Phoenix Metro Area",
    capabilities: ["ambulatory", "wheelchair", "stretcher"],
    activeVehicles: 7,
    memberSince: "2021-11-30",
    verified: true,
  },
];

export const MOCK_MARKETPLACE_TRIPS: MarketplaceTrip[] = [
  {
    id: "mkt-3001",
    tripId: "trip-5001",
    posterId: "org-vmc",
    posterName: "Valley Medical Center",
    cityLevel: "Phoenix, AZ",
    appointmentWindow: { start: timeFromNow(90), end: timeFromNow(120) },
    levelOfService: "wheelchair",
    estimatedMiles: 8.2,
    suggestedPrice: 58.0,
    floorPrice: 42.0,
    ceilingPrice: 75.0,
    currentBestOffer: 52.0,
    status: "open",
    expiresAt: timeFromNow(42),
    specialRequirements: ["wheelchair_ramp"],
    offers: [],
  },
  {
    id: "mkt-3002",
    tripId: "trip-5002",
    posterId: "org-sjh",
    posterName: "St. Joseph's Hospital",
    cityLevel: "Phoenix, AZ",
    appointmentWindow: { start: timeFromNow(60), end: timeFromNow(90) },
    levelOfService: "stretcher",
    estimatedMiles: 14.5,
    suggestedPrice: 195.0,
    floorPrice: 150.0,
    ceilingPrice: 240.0,
    currentBestOffer: 180.0,
    status: "open",
    expiresAt: timeFromNow(18),
    specialRequirements: ["stretcher", "bariatric"],
    offers: [],
  },
  {
    id: "mkt-3003",
    tripId: "trip-5003",
    posterId: "org-bhn",
    posterName: "Banner Health Network",
    cityLevel: "Phoenix, AZ",
    appointmentWindow: { start: timeFromNow(180), end: timeFromNow(210) },
    levelOfService: "ambulatory",
    estimatedMiles: 5.1,
    suggestedPrice: 32.0,
    floorPrice: 22.0,
    ceilingPrice: 45.0,
    currentBestOffer: 28.0,
    status: "offered",
    expiresAt: timeFromNow(75),
    specialRequirements: ["oxygen"],
    offers: [],
  },
  {
    id: "mkt-3004",
    tripId: "trip-5004",
    posterId: "org-vmc",
    posterName: "Valley Medical Center",
    cityLevel: "Scottsdale, AZ",
    appointmentWindow: { start: timeFromNow(240), end: timeFromNow(270) },
    levelOfService: "wheelchair",
    estimatedMiles: 11.3,
    suggestedPrice: 72.0,
    floorPrice: 55.0,
    ceilingPrice: 90.0,
    status: "open",
    expiresAt: timeFromNow(130),
    specialRequirements: ["wheelchair_ramp", "escort"],
    offers: [],
  },
  {
    id: "mkt-3005",
    tripId: "trip-5005",
    posterId: "org-bhn",
    posterName: "Banner Health Network",
    cityLevel: "Scottsdale, AZ",
    appointmentWindow: { start: timeFromNow(300), end: timeFromNow(330) },
    levelOfService: "ambulatory",
    estimatedMiles: 6.8,
    suggestedPrice: 38.0,
    floorPrice: 25.0,
    ceilingPrice: 50.0,
    currentBestOffer: 35.0,
    status: "offered",
    expiresAt: timeFromNow(185),
    specialRequirements: [],
    offers: [],
  },
  {
    id: "mkt-3006",
    tripId: "trip-5006",
    posterId: "org-crh",
    posterName: "Chandler Regional Hospital",
    cityLevel: "Chandler, AZ",
    appointmentWindow: { start: timeFromNow(150), end: timeFromNow(180) },
    levelOfService: "ambulatory",
    estimatedMiles: 4.3,
    suggestedPrice: 26.0,
    floorPrice: 18.0,
    ceilingPrice: 35.0,
    status: "open",
    expiresAt: timeFromNow(55),
    specialRequirements: [],
    offers: [],
  },
  {
    id: "mkt-3007",
    tripId: "trip-5007",
    posterId: "org-dsd",
    posterName: "Desert Springs Dialysis",
    cityLevel: "Mesa, AZ",
    appointmentWindow: { start: timeFromNow(120), end: timeFromNow(150) },
    levelOfService: "wheelchair",
    estimatedMiles: 9.7,
    suggestedPrice: 64.0,
    floorPrice: 48.0,
    ceilingPrice: 82.0,
    currentBestOffer: 60.0,
    status: "offered",
    expiresAt: timeFromNow(65),
    specialRequirements: ["wheelchair_ramp"],
    offers: [],
  },
  {
    id: "mkt-3008",
    tripId: "trip-5008",
    posterId: "org-hon",
    posterName: "HonorHealth Outpatient",
    cityLevel: "Scottsdale, AZ",
    appointmentWindow: { start: timeFromNow(360), end: timeFromNow(390) },
    levelOfService: "stretcher",
    estimatedMiles: 18.2,
    suggestedPrice: 215.0,
    floorPrice: 165.0,
    ceilingPrice: 280.0,
    status: "open",
    expiresAt: timeFromNow(250),
    specialRequirements: ["stretcher", "monitor"],
    offers: [],
  },
  {
    id: "mkt-3009",
    tripId: "trip-5009",
    posterId: "org-vmc",
    posterName: "Valley Medical Center",
    cityLevel: "Phoenix, AZ",
    appointmentWindow: { start: timeFromNow(-60), end: timeFromNow(-30) },
    levelOfService: "ambulatory",
    estimatedMiles: 7.5,
    suggestedPrice: 42.0,
    floorPrice: 30.0,
    ceilingPrice: 55.0,
    currentBestOffer: 38.0,
    status: "accepted",
    expiresAt: timeFromNow(-120),
    specialRequirements: [],
    offers: [],
  },
  {
    id: "mkt-3010",
    tripId: "trip-5010",
    posterId: "org-bhn",
    posterName: "Banner Health Network",
    cityLevel: "Tempe, AZ",
    appointmentWindow: { start: timeFromNow(-180), end: timeFromNow(-150) },
    levelOfService: "wheelchair",
    estimatedMiles: 6.2,
    suggestedPrice: 48.0,
    floorPrice: 35.0,
    ceilingPrice: 62.0,
    status: "completed",
    expiresAt: timeFromNow(-300),
    specialRequirements: ["wheelchair_ramp"],
    offers: [],
  },
  {
    id: "mkt-3011",
    tripId: "trip-5011",
    posterId: "org-crh",
    posterName: "Chandler Regional Hospital",
    cityLevel: "Gilbert, AZ",
    appointmentWindow: { start: timeFromNow(-240), end: timeFromNow(-210) },
    levelOfService: "stretcher",
    estimatedMiles: 12.0,
    suggestedPrice: 165.0,
    floorPrice: 130.0,
    ceilingPrice: 210.0,
    status: "expired",
    expiresAt: timeFromNow(-360),
    specialRequirements: ["stretcher"],
    offers: [],
  },
  {
    id: "mkt-3012",
    tripId: "trip-5012",
    posterId: "org-sjh",
    posterName: "St. Joseph's Hospital",
    cityLevel: "Phoenix, AZ",
    appointmentWindow: { start: timeFromNow(45), end: timeFromNow(75) },
    levelOfService: "bariatric",
    estimatedMiles: 10.5,
    suggestedPrice: 185.0,
    floorPrice: 140.0,
    ceilingPrice: 230.0,
    status: "open",
    expiresAt: timeFromNow(30),
    specialRequirements: ["bariatric", "wheelchair_ramp"],
    offers: [],
  },
];

export const MOCK_MARKETPLACE_OFFERS: MarketplaceOffer[] = [
  {
    id: "offer-4001",
    tripId: "mkt-3001",
    providerId: "provider-001",
    providerName: "SafeRide Medical Transport",
    providerRating: 4.8,
    offeredPrice: 52.0,
    status: "pending",
    submittedAt: timeFromNow(-15),
    credentialVerified: true,
  },
  {
    id: "offer-4002",
    tripId: "mkt-3001",
    providerId: "provider-003",
    providerName: "Desert Care Rides",
    providerRating: 4.2,
    offeredPrice: 55.0,
    status: "pending",
    submittedAt: timeFromNow(-10),
    credentialVerified: true,
  },
  {
    id: "offer-4003",
    tripId: "mkt-3002",
    providerId: "provider-004",
    providerName: "Southwest NEMT Services",
    providerRating: 4.5,
    offeredPrice: 180.0,
    status: "countered",
    counterPrice: 170.0,
    counterNotes: "Can provide BLS-certified attendant at this rate",
    submittedAt: timeFromNow(-25),
    respondedAt: timeFromNow(-20),
    credentialVerified: true,
  },
  {
    id: "offer-4004",
    tripId: "mkt-3003",
    providerId: "provider-001",
    providerName: "SafeRide Medical Transport",
    providerRating: 4.8,
    offeredPrice: 28.0,
    status: "accepted",
    submittedAt: timeFromNow(-60),
    respondedAt: timeFromNow(-45),
    credentialVerified: true,
  },
  {
    id: "offer-4005",
    tripId: "mkt-3005",
    providerId: "provider-006",
    providerName: "Sonoran Express NEMT",
    providerRating: 4.7,
    offeredPrice: 35.0,
    status: "pending",
    submittedAt: timeFromNow(-5),
    credentialVerified: true,
  },
  {
    id: "offer-4006",
    tripId: "mkt-3007",
    providerId: "provider-002",
    providerName: "Valley Medical Transport",
    providerRating: 4.6,
    offeredPrice: 60.0,
    status: "pending",
    submittedAt: timeFromNow(-30),
    credentialVerified: true,
  },
  {
    id: "offer-4007",
    tripId: "mkt-3007",
    providerId: "provider-001",
    providerName: "SafeRide Medical Transport",
    providerRating: 4.8,
    offeredPrice: 58.0,
    status: "countered",
    counterPrice: 55.0,
    counterNotes: "Competitive rate for repeat client facility",
    submittedAt: timeFromNow(-35),
    respondedAt: timeFromNow(-28),
    credentialVerified: true,
  },
  {
    id: "offer-4008",
    tripId: "mkt-3009",
    providerId: "provider-004",
    providerName: "Southwest NEMT Services",
    providerRating: 4.5,
    offeredPrice: 38.0,
    status: "accepted",
    submittedAt: timeFromNow(-180),
    respondedAt: timeFromNow(-150),
    credentialVerified: true,
  },
  {
    id: "offer-4009",
    tripId: "mkt-3010",
    providerId: "provider-006",
    providerName: "Sonoran Express NEMT",
    providerRating: 4.7,
    offeredPrice: 45.0,
    status: "accepted",
    submittedAt: timeFromNow(-360),
    respondedAt: timeFromNow(-340),
    credentialVerified: true,
  },
  {
    id: "offer-4010",
    tripId: "mkt-3002",
    providerId: "provider-001",
    providerName: "SafeRide Medical Transport",
    providerRating: 4.8,
    offeredPrice: 185.0,
    status: "declined",
    submittedAt: timeFromNow(-30),
    respondedAt: timeFromNow(-22),
    credentialVerified: true,
  },
];

export interface SettlementRecord {
  id: string;
  tripId: string;
  offerId: string;
  providerName: string;
  agreedPrice: number;
  status: "pending" | "invoiced" | "paid" | "disputed";
  invoicedAt?: string;
  paidAt?: string;
  paymentMethod?: string;
  tripDate: string;
  levelOfService: string;
  miles: number;
}

export const MOCK_SETTLEMENTS: SettlementRecord[] = [
  {
    id: "stl-5001",
    tripId: "mkt-3009",
    offerId: "offer-4008",
    providerName: "Southwest NEMT Services",
    agreedPrice: 38.0,
    status: "paid",
    invoicedAt: daysAgo(3),
    paidAt: daysAgo(1),
    paymentMethod: "ACH Transfer",
    tripDate: daysAgo(4),
    levelOfService: "Ambulatory",
    miles: 7.5,
  },
  {
    id: "stl-5002",
    tripId: "mkt-3010",
    offerId: "offer-4009",
    providerName: "Sonoran Express NEMT",
    agreedPrice: 45.0,
    status: "paid",
    invoicedAt: daysAgo(5),
    paidAt: daysAgo(2),
    paymentMethod: "ACH Transfer",
    tripDate: daysAgo(7),
    levelOfService: "Wheelchair",
    miles: 6.2,
  },
  {
    id: "stl-5003",
    tripId: "mkt-3003",
    offerId: "offer-4004",
    providerName: "SafeRide Medical Transport",
    agreedPrice: 28.0,
    status: "invoiced",
    invoicedAt: daysAgo(1),
    tripDate: daysAgo(2),
    levelOfService: "Ambulatory",
    miles: 5.1,
  },
  {
    id: "stl-5004",
    tripId: "trip-prev-001",
    offerId: "offer-prev-001",
    providerName: "Valley Medical Transport",
    agreedPrice: 62.0,
    status: "paid",
    invoicedAt: daysAgo(10),
    paidAt: daysAgo(7),
    paymentMethod: "ACH Transfer",
    tripDate: daysAgo(12),
    levelOfService: "Wheelchair",
    miles: 9.3,
  },
  {
    id: "stl-5005",
    tripId: "trip-prev-002",
    offerId: "offer-prev-002",
    providerName: "Desert Care Rides",
    agreedPrice: 155.0,
    status: "disputed",
    invoicedAt: daysAgo(8),
    tripDate: daysAgo(10),
    levelOfService: "Stretcher",
    miles: 13.8,
  },
  {
    id: "stl-5006",
    tripId: "trip-prev-003",
    offerId: "offer-prev-003",
    providerName: "SafeRide Medical Transport",
    agreedPrice: 34.0,
    status: "pending",
    tripDate: daysAgo(1),
    levelOfService: "Ambulatory",
    miles: 4.6,
  },
  {
    id: "stl-5007",
    tripId: "trip-prev-004",
    offerId: "offer-prev-004",
    providerName: "Sonoran Express NEMT",
    agreedPrice: 72.0,
    status: "invoiced",
    invoicedAt: daysAgo(3),
    tripDate: daysAgo(5),
    levelOfService: "Wheelchair",
    miles: 11.1,
  },
  {
    id: "stl-5008",
    tripId: "trip-prev-005",
    offerId: "offer-prev-005",
    providerName: "Copper State Medical Transport",
    agreedPrice: 28.0,
    status: "paid",
    invoicedAt: daysAgo(14),
    paidAt: daysAgo(10),
    paymentMethod: "Check",
    tripDate: daysAgo(16),
    levelOfService: "Ambulatory",
    miles: 5.5,
  },
];

export interface MarketplaceNotification {
  id: string;
  type: "new_trip" | "offer_received" | "offer_accepted" | "offer_countered" | "offer_declined" | "trip_expiring" | "settlement_paid";
  title: string;
  message: string;
  timestamp: string;
  read: boolean;
  tripId?: string;
  offerId?: string;
}

export const MOCK_MARKETPLACE_NOTIFICATIONS: MarketplaceNotification[] = [
  {
    id: "notif-6001",
    type: "new_trip",
    title: "New Stretcher Trip Available",
    message: "St. Joseph's Hospital posted a stretcher trip to Tempe — $195 suggested price, 14.5 mi",
    timestamp: timeFromNow(-5),
    read: false,
    tripId: "mkt-3002",
  },
  {
    id: "notif-6002",
    type: "offer_countered",
    title: "Offer Countered",
    message: "Your offer on MKT-3007 was countered at $55.00 (you offered $58.00)",
    timestamp: timeFromNow(-28),
    read: false,
    tripId: "mkt-3007",
    offerId: "offer-4007",
  },
  {
    id: "notif-6003",
    type: "offer_accepted",
    title: "Offer Accepted!",
    message: "Your offer of $28.00 on MKT-3003 was accepted by Banner Health Network",
    timestamp: timeFromNow(-45),
    read: true,
    tripId: "mkt-3003",
    offerId: "offer-4004",
  },
  {
    id: "notif-6004",
    type: "trip_expiring",
    title: "Trip Expiring Soon",
    message: "MKT-3002 (Stretcher, $195) expires in 18 minutes — only 1 offer so far",
    timestamp: timeFromNow(-2),
    read: false,
    tripId: "mkt-3002",
  },
  {
    id: "notif-6005",
    type: "offer_declined",
    title: "Offer Declined",
    message: "Your offer of $185.00 on MKT-3002 was declined by St. Joseph's Hospital",
    timestamp: timeFromNow(-22),
    read: true,
    tripId: "mkt-3002",
    offerId: "offer-4010",
  },
  {
    id: "notif-6006",
    type: "settlement_paid",
    title: "Payment Received",
    message: "Settlement STL-5001 for $38.00 has been paid via ACH Transfer",
    timestamp: timeFromNow(-60),
    read: true,
  },
  {
    id: "notif-6007",
    type: "new_trip",
    title: "New Bariatric Trip Available",
    message: "St. Joseph's Hospital posted a bariatric trip — $185 suggested price, 10.5 mi",
    timestamp: timeFromNow(-8),
    read: false,
    tripId: "mkt-3012",
  },
  {
    id: "notif-6008",
    type: "offer_received",
    title: "New Offer Received",
    message: "Desert Care Rides offered $55.00 on your posted trip MKT-3001",
    timestamp: timeFromNow(-10),
    read: false,
    tripId: "mkt-3001",
    offerId: "offer-4002",
  },
];

export function getMockPricingResult(miles: number, los: string): PricingResult {
  const baseRates: Record<string, number> = {
    ambulatory: 3.8,
    wheelchair: 5.2,
    stretcher: 12.5,
    bariatric: 14.0,
    bls: 18.0,
  };
  const rate = baseRates[los] || 3.8;
  const base = miles * rate;
  const variance = base * 0.15;

  return {
    suggestedBuyerRate: Math.round((base + variance * 0.3) * 100) / 100,
    suggestedSellerRate: Math.round((base - variance * 0.2) * 100) / 100,
    percentile25: Math.round((base - variance) * 100) / 100,
    percentile75: Math.round((base + variance) * 100) / 100,
    medianRate: Math.round(base * 100) / 100,
    marketIndicator: "at_market",
    confidence: 0.87,
    sampleSize: 342,
    explainabilityText: `Based on ${342} similar ${los} trips in the Phoenix metro area over the past 90 days. Distance of ${miles} mi is near the median for this LOS.`,
    factors: [
      { name: "Distance", impact: miles > 10 ? "increases" : "neutral", weight: 0.35 },
      { name: "Level of Service", impact: los === "stretcher" || los === "bariatric" ? "increases" : "neutral", weight: 0.25 },
      { name: "Time of Day", impact: "neutral", weight: 0.15 },
      { name: "Market Demand", impact: "increases", weight: 0.15 },
      { name: "Provider Availability", impact: "decreases", weight: 0.10 },
    ],
    acceptanceProbability: 0.78,
  };
}

// ============================================================================
// TRACKING MOCK DATA
// ============================================================================

export type { ActiveTracking } from "@/lib/types";

export const MOCK_ACTIVE_TRACKINGS: ActiveTracking[] = [
  {
    tripId: "trip-2002",
    patientName: "James Washington",
    driverName: "Sarah Johnson",
    driverPhone: "(602) 555-0201",
    vehicleDescription: "2023 Mercedes Sprinter - White (V-102)",
    vehicleId: "V-102",
    status: "in_transit",
    pickupLabel: "Home",
    pickupAddress: "890 W Camelback Rd, Phoenix, AZ 85013",
    pickupLat: 33.5093,
    pickupLng: -112.0853,
    dropoffLabel: "Banner University Medical Center",
    dropoffAddress: "1111 E McDowell Rd, Phoenix, AZ 85006",
    dropoffLat: 33.4562,
    dropoffLng: -112.0407,
    driverLat: 33.4780,
    driverLng: -112.0620,
    etaMinutes: 8,
    scheduledTime: todayAt(10, 30),
    levelOfService: "Ambulatory",
    providerName: "SafeRide Medical Transport",
    channel: "Fleet",
    lastUpdated: timeFromNow(-1),
    statusHistory: [
      { status: "Trip Requested", timestamp: todayAt(9, 45), description: "Trip request received from Valley Medical Center" },
      { status: "Driver Assigned", timestamp: todayAt(10, 0), description: "Sarah Johnson assigned (V-102 Mercedes Sprinter)" },
      { status: "En Route to Pickup", timestamp: todayAt(10, 15), description: "Driver departed for pickup location" },
      { status: "At Pickup", timestamp: todayAt(10, 28), description: "Driver arrived at 890 W Camelback Rd" },
      { status: "Patient Picked Up", timestamp: todayAt(10, 32), description: "Patient boarded, en route to destination" },
    ],
  },
  {
    tripId: "trip-2003",
    patientName: "Robert Kim",
    driverName: "Lisa Park",
    driverPhone: "(602) 555-0312",
    vehicleDescription: "2022 Toyota Sienna - Silver (V-104)",
    vehicleId: "V-104",
    status: "en_route_pickup",
    pickupLabel: "Home",
    pickupAddress: "5678 E McDowell Rd, Phoenix, AZ 85008",
    pickupLat: 33.4655,
    pickupLng: -111.9988,
    dropoffLabel: "Mayo Clinic - Phoenix",
    dropoffAddress: "5777 E Mayo Blvd, Phoenix, AZ 85054",
    dropoffLat: 33.6598,
    dropoffLng: -111.9578,
    driverLat: 33.4700,
    driverLng: -112.0200,
    etaMinutes: 12,
    scheduledTime: todayAt(13, 0),
    levelOfService: "Ambulatory",
    providerName: "SafeRide Medical Transport",
    channel: "Fleet",
    lastUpdated: timeFromNow(-2),
    statusHistory: [
      { status: "Trip Requested", timestamp: todayAt(12, 15), description: "Trip request received from Banner Health Network" },
      { status: "Driver Assigned", timestamp: todayAt(12, 30), description: "Lisa Park assigned (V-104 Toyota Sienna)" },
      { status: "En Route to Pickup", timestamp: todayAt(12, 45), description: "Driver departed for pickup location" },
    ],
  },
  {
    tripId: "trip-2004",
    patientName: "Dorothy Chen",
    driverName: "Angela Torres",
    driverPhone: "(602) 555-0423",
    vehicleDescription: "2023 Ford E-Transit Stretcher Van (V-108)",
    vehicleId: "V-108",
    status: "driver_assigned",
    pickupLabel: "Home",
    pickupAddress: "3400 N Central Ave, Phoenix, AZ 85012",
    pickupLat: 33.4942,
    pickupLng: -112.0739,
    dropoffLabel: "St. Joseph's Hospital",
    dropoffAddress: "350 W Thomas Rd, Phoenix, AZ 85013",
    dropoffLat: 33.4813,
    dropoffLng: -112.0815,
    driverLat: 33.5100,
    driverLng: -112.0500,
    etaMinutes: 25,
    scheduledTime: todayAt(14, 30),
    levelOfService: "Stretcher",
    providerName: "SafeRide Medical Transport",
    channel: "Fleet",
    lastUpdated: timeFromNow(-5),
    statusHistory: [
      { status: "Trip Requested", timestamp: todayAt(13, 45), description: "Trip request received from Chandler Regional Hospital" },
      { status: "Driver Assigned", timestamp: todayAt(14, 0), description: "Angela Torres assigned (V-108 Stretcher Van)" },
    ],
  },
  {
    tripId: "trip-2005",
    patientName: "Maria Gonzalez",
    driverName: "Carlos Mendez",
    driverPhone: "(602) 555-0534",
    vehicleDescription: "2022 Ford Transit (V-101)",
    vehicleId: "V-101",
    status: "at_pickup",
    pickupLabel: "Kaiser Permanente Central",
    pickupAddress: "2100 E Highland Ave, Phoenix, AZ 85016",
    pickupLat: 33.5097,
    pickupLng: -112.0344,
    dropoffLabel: "Home",
    dropoffAddress: "1234 E Oak St, Phoenix, AZ 85006",
    dropoffLat: 33.4484,
    dropoffLng: -112.0548,
    driverLat: 33.5097,
    driverLng: -112.0344,
    etaMinutes: 3,
    scheduledTime: todayAt(11, 0),
    levelOfService: "Wheelchair",
    providerName: "SafeRide Medical Transport",
    channel: "Marketplace",
    lastUpdated: timeFromNow(0),
    statusHistory: [
      { status: "Trip Requested", timestamp: todayAt(10, 0), description: "Trip request via marketplace from Valley Medical Center" },
      { status: "Offer Accepted", timestamp: todayAt(10, 5), description: "SafeRide Medical Transport accepted at $28.00" },
      { status: "Driver Assigned", timestamp: todayAt(10, 10), description: "Carlos Mendez assigned (V-101 Ford Transit)" },
      { status: "En Route to Pickup", timestamp: todayAt(10, 40), description: "Driver departed for pickup location" },
      { status: "At Pickup", timestamp: todayAt(10, 55), description: "Driver arrived at Kaiser Permanente Central" },
    ],
  },
  {
    tripId: "trip-2006",
    patientName: "Helen Park",
    driverName: "Uber Driver - Ahmad R.",
    driverPhone: "(602) 555-0645",
    vehicleDescription: "2024 Honda Accord - Black (Uber WAV)",
    vehicleId: "UBR-8821",
    status: "at_dropoff",
    pickupLabel: "Home",
    pickupAddress: "4120 W Indian School Rd, Phoenix, AZ 85019",
    pickupLat: 33.4942,
    pickupLng: -112.1142,
    dropoffLabel: "Banner Desert Medical Center",
    dropoffAddress: "1400 S Dobson Rd, Mesa, AZ 85202",
    dropoffLat: 33.3882,
    dropoffLng: -111.8767,
    driverLat: 33.3885,
    driverLng: -111.8770,
    etaMinutes: 1,
    scheduledTime: todayAt(9, 30),
    levelOfService: "Ambulatory",
    providerName: "Uber Health",
    channel: "TNC",
    lastUpdated: timeFromNow(0),
    statusHistory: [
      { status: "Trip Requested", timestamp: todayAt(9, 0), description: "TNC ride requested via Uber Health" },
      { status: "Driver Assigned", timestamp: todayAt(9, 8), description: "Ahmad R. assigned (Honda Accord)" },
      { status: "En Route to Pickup", timestamp: todayAt(9, 10), description: "Driver en route to pickup" },
      { status: "At Pickup", timestamp: todayAt(9, 22), description: "Driver arrived at pickup" },
      { status: "Patient Picked Up", timestamp: todayAt(9, 25), description: "Patient boarded vehicle" },
      { status: "At Dropoff", timestamp: todayAt(9, 52), description: "Arrived at Banner Desert Medical Center" },
    ],
  },
  {
    tripId: "trip-2007",
    patientName: "Frank Martinez",
    driverName: "Michael Okafor",
    driverPhone: "(602) 555-0305",
    vehicleDescription: "2021 Dodge Grand Caravan - Gray (V-103)",
    vehicleId: "V-103",
    status: "en_route_pickup",
    pickupLabel: "Desert Springs Dialysis",
    pickupAddress: "2020 W Bethany Home Rd, Phoenix, AZ 85015",
    pickupLat: 33.5243,
    pickupLng: -112.0891,
    dropoffLabel: "Home",
    dropoffAddress: "6430 S 32nd St, Phoenix, AZ 85042",
    dropoffLat: 33.3922,
    dropoffLng: -112.0203,
    driverLat: 33.5100,
    driverLng: -112.0700,
    etaMinutes: 6,
    scheduledTime: todayAt(13, 30),
    levelOfService: "Ambulatory",
    providerName: "Valley Medical Transport",
    channel: "Marketplace",
    lastUpdated: timeFromNow(-1),
    statusHistory: [
      { status: "Trip Requested", timestamp: todayAt(12, 30), description: "Marketplace trip posted by Desert Springs Dialysis" },
      { status: "Offer Accepted", timestamp: todayAt(12, 45), description: "Valley Medical Transport accepted at $32.00" },
      { status: "Driver Assigned", timestamp: todayAt(13, 0), description: "Michael Okafor assigned (V-103 Dodge Grand Caravan)" },
      { status: "En Route to Pickup", timestamp: todayAt(13, 20), description: "Driver departed for pickup location" },
    ],
  },
];

// ============================================================================
// HEALTH PLAN MOCK DATA
// ============================================================================

export const MOCK_HEALTH_PLANS: HealthPlan[] = [
  {
    id: "hp-az-medicaid-001",
    name: "Arizona Complete Health",
    organizationId: "org-ach",
    type: "medicaid_mco",
    products: [
      {
        id: "prod-ach-standard",
        name: "AHCCCS Standard",
        benefitConfig: {
          maxTripsPerYear: 52,
          maxMilesPerTrip: 60,
          coveredLOS: ["ambulatory", "wheelchair", "stretcher"],
          requiresAuthorization: false,
          copay: 0,
          coinsurancePercent: 0,
          escortCovered: true,
          maxEscorts: 1,
          willCallAllowed: true,
          roundTripAllowed: true,
        },
      },
      {
        id: "prod-ach-enhanced",
        name: "AHCCCS Enhanced",
        benefitConfig: {
          maxTripsPerYear: 104,
          maxMilesPerTrip: 100,
          coveredLOS: ["ambulatory", "wheelchair", "stretcher", "bariatric"],
          requiresAuthorization: false,
          copay: 0,
          coinsurancePercent: 0,
          escortCovered: true,
          maxEscorts: 2,
          willCallAllowed: true,
          roundTripAllowed: true,
        },
      },
    ],
  },
  {
    id: "hp-az-medicare-002",
    name: "UnitedHealthcare Medicare Advantage",
    organizationId: "org-uhc",
    type: "medicare_advantage",
    products: [
      {
        id: "prod-uhc-basic",
        name: "Medicare Advantage Basic",
        benefitConfig: {
          maxTripsPerYear: 24,
          maxMilesPerTrip: 40,
          coveredLOS: ["ambulatory", "wheelchair"],
          requiresAuthorization: true,
          copay: 5,
          coinsurancePercent: 10,
          escortCovered: false,
          maxEscorts: 0,
          willCallAllowed: false,
          roundTripAllowed: true,
        },
      },
      {
        id: "prod-uhc-premium",
        name: "Medicare Advantage Premium",
        benefitConfig: {
          maxTripsPerYear: 48,
          maxMilesPerTrip: 75,
          coveredLOS: ["ambulatory", "wheelchair", "stretcher", "bariatric"],
          requiresAuthorization: true,
          copay: 0,
          coinsurancePercent: 5,
          escortCovered: true,
          maxEscorts: 1,
          willCallAllowed: true,
          roundTripAllowed: true,
        },
      },
    ],
  },
  {
    id: "hp-az-commercial-003",
    name: "Blue Cross Blue Shield of Arizona",
    organizationId: "org-bcbs",
    type: "commercial",
    products: [
      {
        id: "prod-bcbs-standard",
        name: "Commercial Standard PPO",
        benefitConfig: {
          maxTripsPerYear: 12,
          maxMilesPerTrip: 30,
          coveredLOS: ["ambulatory"],
          requiresAuthorization: true,
          copay: 15,
          coinsurancePercent: 20,
          escortCovered: false,
          maxEscorts: 0,
          willCallAllowed: false,
          roundTripAllowed: false,
        },
      },
    ],
  },
];

export const MOCK_AUTH_RULES: AuthorizationRule[] = [
  {
    id: "auth-rule-001",
    name: "Auto-Approve Routine Dialysis",
    healthPlanId: "hp-az-medicaid-001",
    conditions: [
      { field: "levelOfService", operator: "eq", value: "ambulatory" },
      { field: "distance", operator: "lt", value: 20 },
      { field: "tripPurpose", operator: "eq", value: "dialysis" },
    ],
    action: "auto_approve",
    priority: 1,
    active: true,
  },
  {
    id: "auth-rule-002",
    name: "Review Long-Distance Trips",
    healthPlanId: "hp-az-medicaid-001",
    conditions: [
      { field: "distance", operator: "gt", value: 50 },
    ],
    action: "require_review",
    priority: 2,
    active: true,
  },
  {
    id: "auth-rule-003",
    name: "Deny Exceeded Trip Limit",
    healthPlanId: "hp-az-medicaid-001",
    conditions: [
      { field: "tripsUsed", operator: "gt", value: 52 },
    ],
    action: "deny",
    priority: 3,
    active: true,
  },
  {
    id: "auth-rule-004",
    name: "Auto-Approve Wheelchair Under 15 Miles",
    healthPlanId: "hp-az-medicare-002",
    conditions: [
      { field: "levelOfService", operator: "eq", value: "wheelchair" },
      { field: "distance", operator: "lt", value: 15 },
    ],
    action: "auto_approve",
    priority: 1,
    active: true,
  },
  {
    id: "auth-rule-005",
    name: "Review All Stretcher Requests",
    healthPlanId: "hp-az-medicare-002",
    conditions: [
      { field: "levelOfService", operator: "in", value: ["stretcher", "bariatric"] },
    ],
    action: "require_review",
    priority: 2,
    active: true,
  },
  {
    id: "auth-rule-006",
    name: "Deny Non-Covered LOS",
    healthPlanId: "hp-az-commercial-003",
    conditions: [
      { field: "levelOfService", operator: "in", value: ["stretcher", "bariatric", "bls"] },
    ],
    action: "deny",
    priority: 1,
    active: true,
  },
];

export interface HealthPlanMember {
  id: string;
  firstName: string;
  lastName: string;
  memberId: string;
  healthPlanId: string;
  healthPlanName: string;
  productName: string;
  eligibilityStatus: "eligible" | "pending" | "ineligible" | "suspended";
  tripsUsed: number;
  tripsAuthorized: number;
  lastTripDate: string;
  mobilityType: string;
  phone: string;
  city: string;
}

export const MOCK_HP_MEMBERS: HealthPlanMember[] = [
  {
    id: "pat-001",
    firstName: "Maria",
    lastName: "Gonzalez",
    memberId: "MBR-44892",
    healthPlanId: "hp-az-medicaid-001",
    healthPlanName: "Arizona Complete Health",
    productName: "AHCCCS Standard",
    eligibilityStatus: "eligible",
    tripsUsed: 34,
    tripsAuthorized: 52,
    lastTripDate: daysAgo(2),
    mobilityType: "Wheelchair",
    phone: "(602) 555-0134",
    city: "Phoenix",
  },
  {
    id: "pat-002",
    firstName: "James",
    lastName: "Washington",
    memberId: "MBR-33107",
    healthPlanId: "hp-az-medicare-002",
    healthPlanName: "UnitedHealthcare Medicare Advantage",
    productName: "Medicare Advantage Basic",
    eligibilityStatus: "eligible",
    tripsUsed: 18,
    tripsAuthorized: 24,
    lastTripDate: daysAgo(0),
    mobilityType: "Ambulatory",
    phone: "(602) 555-0278",
    city: "Phoenix",
  },
  {
    id: "pat-003",
    firstName: "Dorothy",
    lastName: "Chen",
    memberId: "MBR-55201",
    healthPlanId: "hp-az-medicaid-001",
    healthPlanName: "Arizona Complete Health",
    productName: "AHCCCS Enhanced",
    eligibilityStatus: "pending",
    tripsUsed: 67,
    tripsAuthorized: 104,
    lastTripDate: daysAgo(5),
    mobilityType: "Stretcher",
    phone: "(602) 555-0391",
    city: "Phoenix",
  },
  {
    id: "pat-004",
    firstName: "Robert",
    lastName: "Kim",
    memberId: "MBR-21058",
    healthPlanId: "hp-az-commercial-003",
    healthPlanName: "Blue Cross Blue Shield of Arizona",
    productName: "Commercial Standard PPO",
    eligibilityStatus: "eligible",
    tripsUsed: 8,
    tripsAuthorized: 12,
    lastTripDate: daysAgo(1),
    mobilityType: "Ambulatory",
    phone: "(602) 555-0445",
    city: "Phoenix",
  },
  {
    id: "pat-005",
    firstName: "Helen",
    lastName: "Park",
    memberId: "MBR-67234",
    healthPlanId: "hp-az-medicaid-001",
    healthPlanName: "Arizona Complete Health",
    productName: "AHCCCS Standard",
    eligibilityStatus: "eligible",
    tripsUsed: 12,
    tripsAuthorized: 52,
    lastTripDate: daysAgo(3),
    mobilityType: "Ambulatory",
    phone: "(602) 555-0567",
    city: "Scottsdale",
  },
  {
    id: "pat-006",
    firstName: "Frank",
    lastName: "Martinez",
    memberId: "MBR-78901",
    healthPlanId: "hp-az-medicare-002",
    healthPlanName: "UnitedHealthcare Medicare Advantage",
    productName: "Medicare Advantage Premium",
    eligibilityStatus: "eligible",
    tripsUsed: 42,
    tripsAuthorized: 48,
    lastTripDate: daysAgo(0),
    mobilityType: "Wheelchair",
    phone: "(602) 555-0678",
    city: "Tempe",
  },
  {
    id: "pat-007",
    firstName: "Susan",
    lastName: "Williams",
    memberId: "MBR-34567",
    healthPlanId: "hp-az-medicaid-001",
    healthPlanName: "Arizona Complete Health",
    productName: "AHCCCS Standard",
    eligibilityStatus: "suspended",
    tripsUsed: 52,
    tripsAuthorized: 52,
    lastTripDate: daysAgo(14),
    mobilityType: "Ambulatory",
    phone: "(602) 555-0789",
    city: "Mesa",
  },
  {
    id: "pat-008",
    firstName: "Thomas",
    lastName: "Anderson",
    memberId: "MBR-45678",
    healthPlanId: "hp-az-commercial-003",
    healthPlanName: "Blue Cross Blue Shield of Arizona",
    productName: "Commercial Standard PPO",
    eligibilityStatus: "ineligible",
    tripsUsed: 12,
    tripsAuthorized: 12,
    lastTripDate: daysAgo(30),
    mobilityType: "Ambulatory",
    phone: "(602) 555-0890",
    city: "Chandler",
  },
];

// ============================================================================
// BROKER SLA COMPLIANCE METRICS
// ============================================================================

export const MOCK_COMPLIANCE_METRICS: ComplianceMetric[] = [
  {
    broker: "modivcare",
    brokerLabel: "ModivCare",
    onTimePercent: 94.2,
    noShowPercent: 2.1,
    complaintRate: 0.8,
    avgResponseMinutes: 4.3,
    slaTarget: 92,
    tripsThisMonth: 1247,
    credentialCompliance: 98,
  },
  {
    broker: "mtm",
    brokerLabel: "MTM",
    onTimePercent: 89.5,
    noShowPercent: 3.8,
    complaintRate: 1.9,
    avgResponseMinutes: 6.1,
    slaTarget: 93,
    tripsThisMonth: 834,
    credentialCompliance: 91,
  },
  {
    broker: "saferide",
    brokerLabel: "SafeRide Health",
    onTimePercent: 96.8,
    noShowPercent: 1.4,
    complaintRate: 0.5,
    avgResponseMinutes: 3.2,
    slaTarget: 95,
    tripsThisMonth: 562,
    credentialCompliance: 99,
  },
  {
    broker: "alivi",
    brokerLabel: "Alivi",
    onTimePercent: 91.3,
    noShowPercent: 2.9,
    complaintRate: 1.2,
    avgResponseMinutes: 8.4,
    slaTarget: 90,
    tripsThisMonth: 421,
    credentialCompliance: 94,
  },
];

// ============================================================================
// BROKER CLAIMS
// ============================================================================

export const MOCK_BROKER_CLAIMS: Claim[] = [
  {
    id: "CL-00001001",
    tripId: "TRP-5520",
    brokerReference: "MOD-88432",
    status: "paid",
    amount: 145.0,
    submittedAt: daysAgo(14),
    paidAt: daysAgo(3),
  },
  {
    id: "CL-00001002",
    tripId: "TRP-5519",
    brokerReference: "MTM-20145",
    status: "approved",
    amount: 210.5,
    submittedAt: daysAgo(10),
  },
  {
    id: "CL-00001003",
    tripId: "TRP-5518",
    brokerReference: "MOD-88440",
    status: "denied",
    amount: 320.0,
    submittedAt: daysAgo(12),
    denialReason: "Service not pre-authorized for this member",
  },
  {
    id: "CL-00001004",
    tripId: "TRP-5517",
    brokerReference: "SR-77201",
    status: "under_review",
    amount: 175.25,
    submittedAt: daysAgo(5),
  },
  {
    id: "CL-00001005",
    tripId: "TRP-5516",
    brokerReference: "MOD-88455",
    status: "submitted",
    amount: 89.0,
    submittedAt: daysAgo(2),
  },
  {
    id: "CL-00001006",
    tripId: "TRP-5515",
    brokerReference: "ALV-30012",
    status: "draft",
    amount: 265.75,
  },
  {
    id: "CL-00001007",
    tripId: "TRP-5514",
    brokerReference: "MTM-20160",
    status: "paid",
    amount: 198.0,
    submittedAt: daysAgo(21),
    paidAt: daysAgo(7),
  },
  {
    id: "CL-00001008",
    tripId: "TRP-5513",
    brokerReference: "MOD-88461",
    status: "denied",
    amount: 412.5,
    submittedAt: daysAgo(18),
    denialReason: "Duplicate claim — already processed under CL-00000998",
  },
  {
    id: "CL-00001009",
    tripId: "TRP-5512",
    brokerReference: "SR-77215",
    status: "submitted",
    amount: 134.0,
    submittedAt: daysAgo(1),
  },
  {
    id: "CL-00001010",
    tripId: "TRP-5511",
    brokerReference: "ALV-30025",
    status: "draft",
    amount: 187.5,
  },
  {
    id: "CL-00001011",
    tripId: "TRP-5510",
    brokerReference: "MTM-20178",
    status: "approved",
    amount: 156.0,
    submittedAt: daysAgo(8),
  },
  {
    id: "CL-00001012",
    tripId: "TRP-5509",
    brokerReference: "MOD-88470",
    status: "paid",
    amount: 278.25,
    submittedAt: daysAgo(30),
    paidAt: daysAgo(15),
  },
];

// ============================================================================
// BROKER TRIP IMPORTS
// ============================================================================

export const MOCK_BROKER_IMPORTS: BrokerTripImport[] = [
  {
    id: "imp-001",
    brokerSystem: "modivcare",
    externalId: "MDV-2024-78321",
    importedAt: daysAgo(0),
    patient: { name: "Maria Gonzalez", phone: "(602) 555-0112" },
    pickup: {
      label: "Home",
      street: "4521 W Camelback Rd",
      city: "Phoenix",
      state: "AZ",
      zip: "85031",
      lat: 33.5098,
      lng: -112.1535,
    },
    dropoff: {
      label: "Banner Health Clinic",
      street: "1441 N 12th St",
      city: "Phoenix",
      state: "AZ",
      zip: "85006",
      lat: 33.4622,
      lng: -112.0567,
    },
    requestedDate: todayAt(10, 0),
    requestedTime: "10:00 AM",
    levelOfService: "wheelchair",
    syncStatus: "synced",
    lastSyncAt: timeFromNow(-15),
    internalTripId: "TRP-20240115-001",
  },
  {
    id: "imp-002",
    brokerSystem: "mtm",
    externalId: "MTM-AZ-44219",
    importedAt: daysAgo(0),
    patient: { name: "James Washington", phone: "(480) 555-0234" },
    pickup: {
      label: "Sunrise Senior Living",
      street: "7878 E Gainey Ranch Rd",
      city: "Scottsdale",
      state: "AZ",
      zip: "85258",
      lat: 33.5656,
      lng: -111.9283,
    },
    dropoff: {
      label: "Mayo Clinic",
      street: "5777 E Mayo Blvd",
      city: "Phoenix",
      state: "AZ",
      zip: "85054",
      lat: 33.6589,
      lng: -111.9535,
    },
    requestedDate: todayAt(14, 30),
    requestedTime: "2:30 PM",
    levelOfService: "ambulatory",
    syncStatus: "pending",
    lastSyncAt: timeFromNow(-45),
  },
  {
    id: "imp-003",
    brokerSystem: "saferide",
    externalId: "SR-092-55810",
    importedAt: daysAgo(1),
    patient: { name: "Dorothy Chen", phone: "(623) 555-0345" },
    pickup: {
      label: "Desert Palms Care Center",
      street: "13840 N Cave Creek Rd",
      city: "Phoenix",
      state: "AZ",
      zip: "85022",
      lat: 33.6102,
      lng: -112.0252,
    },
    dropoff: {
      label: "St. Joseph's Hospital",
      street: "350 W Thomas Rd",
      city: "Phoenix",
      state: "AZ",
      zip: "85013",
      lat: 33.4813,
      lng: -112.0820,
    },
    requestedDate: todayAt(9, 0),
    requestedTime: "9:00 AM",
    levelOfService: "stretcher",
    syncStatus: "synced",
    lastSyncAt: timeFromNow(-120),
    internalTripId: "TRP-20240114-008",
  },
  {
    id: "imp-004",
    brokerSystem: "modivcare",
    externalId: "MDV-2024-78345",
    importedAt: daysAgo(0),
    patient: { name: "Robert Kim", phone: "(602) 555-0456" },
    pickup: {
      label: "Home",
      street: "2200 E Camelback Rd",
      city: "Phoenix",
      state: "AZ",
      zip: "85016",
      lat: 33.5092,
      lng: -112.0321,
    },
    dropoff: {
      label: "Dignity Health Clinic",
      street: "3330 N 2nd St",
      city: "Phoenix",
      state: "AZ",
      zip: "85012",
      lat: 33.4790,
      lng: -112.0690,
    },
    requestedDate: todayAt(11, 15),
    requestedTime: "11:15 AM",
    levelOfService: "ambulatory",
    syncStatus: "error",
    lastSyncAt: timeFromNow(-60),
  },
  {
    id: "imp-005",
    brokerSystem: "alivi",
    externalId: "ALV-30092-A",
    importedAt: daysAgo(2),
    patient: { name: "Helen Park", phone: "(480) 555-0567" },
    pickup: {
      label: "Home",
      street: "1055 W Ray Rd",
      city: "Chandler",
      state: "AZ",
      zip: "85224",
      lat: 33.3186,
      lng: -111.8549,
    },
    dropoff: {
      label: "Chandler Regional Medical Center",
      street: "1955 W Frye Rd",
      city: "Chandler",
      state: "AZ",
      zip: "85224",
      lat: 33.3039,
      lng: -111.8560,
    },
    requestedDate: todayAt(8, 0),
    requestedTime: "8:00 AM",
    levelOfService: "ambulatory",
    syncStatus: "stale",
    lastSyncAt: daysAgo(2),
    internalTripId: "TRP-20240112-014",
  },
  {
    id: "imp-006",
    brokerSystem: "mtm",
    externalId: "MTM-AZ-44235",
    importedAt: daysAgo(0),
    patient: { name: "Frank Martinez", phone: "(602) 555-0678" },
    pickup: {
      label: "Home",
      street: "3802 N 32nd St",
      city: "Phoenix",
      state: "AZ",
      zip: "85018",
      lat: 33.4951,
      lng: -112.0154,
    },
    dropoff: {
      label: "HonorHealth Shea",
      street: "9003 E Shea Blvd",
      city: "Scottsdale",
      state: "AZ",
      zip: "85260",
      lat: 33.5813,
      lng: -111.8910,
    },
    requestedDate: todayAt(13, 0),
    requestedTime: "1:00 PM",
    levelOfService: "wheelchair",
    syncStatus: "synced",
    lastSyncAt: timeFromNow(-30),
    internalTripId: "TRP-20240115-005",
  },
  {
    id: "imp-007",
    brokerSystem: "saferide",
    externalId: "SR-092-55824",
    importedAt: daysAgo(0),
    patient: { name: "Susan Williams", phone: "(623) 555-0789" },
    pickup: {
      label: "Arrowhead Senior Center",
      street: "7550 W Olive Ave",
      city: "Peoria",
      state: "AZ",
      zip: "85345",
      lat: 33.5325,
      lng: -112.2408,
    },
    dropoff: {
      label: "Banner Thunderbird Medical",
      street: "5555 W Thunderbird Rd",
      city: "Glendale",
      state: "AZ",
      zip: "85306",
      lat: 33.6107,
      lng: -112.1838,
    },
    requestedDate: todayAt(15, 0),
    requestedTime: "3:00 PM",
    levelOfService: "ambulatory",
    syncStatus: "pending",
    lastSyncAt: timeFromNow(-10),
  },
  {
    id: "imp-008",
    brokerSystem: "alivi",
    externalId: "ALV-30098-B",
    importedAt: daysAgo(1),
    patient: { name: "Thomas Anderson", phone: "(602) 555-0890" },
    pickup: {
      label: "Home",
      street: "5050 N 40th St",
      city: "Phoenix",
      state: "AZ",
      zip: "85018",
      lat: 33.5060,
      lng: -112.0092,
    },
    dropoff: {
      label: "Phoenix VA Health Care",
      street: "650 E Indian School Rd",
      city: "Phoenix",
      state: "AZ",
      zip: "85012",
      lat: 33.4953,
      lng: -112.0633,
    },
    requestedDate: todayAt(10, 45),
    requestedTime: "10:45 AM",
    levelOfService: "ambulatory",
    syncStatus: "error",
    lastSyncAt: timeFromNow(-90),
  },
  {
    id: "imp-009",
    brokerSystem: "modivcare",
    externalId: "MDV-2024-78401",
    importedAt: daysAgo(0),
    patient: { name: "Patricia Davis", phone: "(480) 555-0901" },
    pickup: {
      label: "Home",
      street: "1828 E Southern Ave",
      city: "Tempe",
      state: "AZ",
      zip: "85282",
      lat: 33.3917,
      lng: -111.9099,
    },
    dropoff: {
      label: "Tempe St. Luke's Hospital",
      street: "1500 S Mill Ave",
      city: "Tempe",
      state: "AZ",
      zip: "85281",
      lat: 33.4148,
      lng: -111.9400,
    },
    requestedDate: todayAt(16, 0),
    requestedTime: "4:00 PM",
    levelOfService: "ambulatory",
    syncStatus: "synced",
    lastSyncAt: timeFromNow(-5),
    internalTripId: "TRP-20240115-011",
  },
  {
    id: "imp-010",
    brokerSystem: "mtm",
    externalId: "MTM-AZ-44250",
    importedAt: daysAgo(1),
    patient: { name: "William Brown", phone: "(623) 555-1012" },
    pickup: {
      label: "West Valley Rehab",
      street: "13620 N Saguaro Blvd",
      city: "Fountain Hills",
      state: "AZ",
      zip: "85268",
      lat: 33.6022,
      lng: -111.7177,
    },
    dropoff: {
      label: "Banner Gateway Medical",
      street: "1900 N Higley Rd",
      city: "Gilbert",
      state: "AZ",
      zip: "85234",
      lat: 33.3664,
      lng: -111.7213,
    },
    requestedDate: todayAt(12, 0),
    requestedTime: "12:00 PM",
    levelOfService: "bariatric",
    syncStatus: "synced",
    lastSyncAt: timeFromNow(-180),
    internalTripId: "TRP-20240114-019",
  },
  {
    id: "imp-011",
    brokerSystem: "saferide",
    externalId: "SR-092-55837",
    importedAt: daysAgo(0),
    patient: { name: "Linda Taylor", phone: "(602) 555-1123" },
    pickup: {
      label: "Home",
      street: "2101 W Bethany Home Rd",
      city: "Phoenix",
      state: "AZ",
      zip: "85015",
      lat: 33.5230,
      lng: -112.0940,
    },
    dropoff: {
      label: "Abrazo Central Campus",
      street: "2000 W Bethany Home Rd",
      city: "Phoenix",
      state: "AZ",
      zip: "85015",
      lat: 33.5231,
      lng: -112.0915,
    },
    requestedDate: todayAt(7, 30),
    requestedTime: "7:30 AM",
    levelOfService: "wheelchair",
    syncStatus: "synced",
    lastSyncAt: timeFromNow(-8),
    internalTripId: "TRP-20240115-003",
  },
  {
    id: "imp-012",
    brokerSystem: "alivi",
    externalId: "ALV-30105-C",
    importedAt: daysAgo(0),
    patient: { name: "Richard Lopez", phone: "(480) 555-1234" },
    pickup: {
      label: "Mesa Adult Day Center",
      street: "247 N Macdonald St",
      city: "Mesa",
      state: "AZ",
      zip: "85201",
      lat: 33.4152,
      lng: -111.8315,
    },
    dropoff: {
      label: "Banner Desert Medical Center",
      street: "1400 S Dobson Rd",
      city: "Mesa",
      state: "AZ",
      zip: "85202",
      lat: 33.3886,
      lng: -111.8776,
    },
    requestedDate: todayAt(14, 0),
    requestedTime: "2:00 PM",
    levelOfService: "ambulatory",
    syncStatus: "pending",
    lastSyncAt: timeFromNow(-20),
  },
];
